---
apiVersion: v1
kind: Template
metadata:
  name: ${SHARED_DB_APP_NAME}-floorist
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ${SHARED_DB_APP_NAME}-floorist
  spec:
    database:
      sharedDbAppName: ${SHARED_DB_APP_NAME}
    dependencies:
      - ${SHARED_DB_APP_NAME}
    objectStore:
      - ${BUCKET_NAME}
    envName: ${ENV_NAME}
    jobs:
    - name: metrics-exporter
      schedule: ${FLOORIST_SCHEDULE}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: AWS_BUCKET
          value: ${BUCKET_NAME}
        - name: FLOORPLAN_FILE
          value: "/tmp/floorplan/floorplan.yaml"
        volumeMounts:
        - name: floorplan-volume
          mountPath: "/tmp/floorplan"
        volumes:
          - name: floorplan-volume
            configMap:
              name: floorplan
      resources:
          limits:
            cpu: "${CPU_LIMIT}"
            memory: "${MEMORY_LIMIT}"
          requests:
            cpu: "${CPU_REQUEST}"
            memory: "${MEMORY_REQUEST}"

parameters:
- description: Shared DB ClowdApp name
  name: SHARED_DB_APP_NAME
  required: true
- description: Shared bucket name
  name: BUCKET_NAME
  required: true
  value: floorist-bucket
- description: Image tag
  name: IMAGE_TAG
  required: true
  value: latest
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/floorist
- description: ClowdEnv Name
  name: ENV_NAME
- name: MEMORY_LIMIT
  value: 200Mi
- name: MEMORY_REQUEST
  value: 100Mi
- name: CPU_LIMIT
  value: 100m
- name: CPU_REQUEST
  value: 50m
- name: FLOORIST_SCHEDULE
  description: Cronjob schedule definition
  required: true
