name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: quay.io/cloudservices/postgresql-rds:16
        env:
          POSTGRESQL_USER: postgres_user
          POSTGRESQL_PASSWORD: remediations
          POSTGRESQL_DATABASE: remediationstest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: is fork
        run: echo "${{ github.event.repository.fork }}"

      - name: debug
        run: |
          echo "$TEST_CREDS"
        env:
          TEST_CREDS: ${{ secrets.TEST_CREDS }}

      - name: Debug TEST_CREDS
        run: |
          if [ -z "${TEST_CREDS}" ]; then
            echo "TEST_CREDS is not set."
          else
            echo "TEST_CREDS is set."
          fi
        env:
          TEST_CREDS: ${{ secrets.TEST_CREDS }}

      - name: debug run
        run: podman pull registry.redhat.io/rhel9/postgresql-13

      - name: Run tests
        shell: bash
        run: ./pr_check.sh
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          RH_REGISTRY_USER: ${{ secrets.QUAY_USER }}
          RH_REGISTRY_TOKEN: ${{ secrets.QUAY_TOKEN }}
          QUAY_REGISTRY: quay.io
          REDHAT_REGISTRY: quay.io
          LOCAL_BUILD: true
